---
- hosts: YumRepoRpmForge_servers
  max_fail_percentage: 1
  serial: 1
  accelerate: false
  sudo: true


  roles:
    # configure /etc/resolv.conf
    #
    - Azulinho.azulinho-google-dns

    - yum-repo-rpmforge

